<a href="https://colab.research.google.com/github/chloepark627/tensorflow_ex/blob/master/ch07_RNN(7_2_layers).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
X = list(); Y = list();
for i in range(6):
    lst = list(range(i, i+4)) 
    #0 / 0,1,2,3
    print('i : ', lst, i+4)

    x = list(map(lambda c:[c/10], lst))
    y = (i+4)/10
    X.append(x)
    Y.append(y)

    print('X : ', x)
    print('Y : ', y)
    print()

i :  [0, 1, 2, 3] 4
X :  [[0.0], [0.1], [0.2], [0.3]]
Y :  0.4

i :  [1, 2, 3, 4] 5
X :  [[0.1], [0.2], [0.3], [0.4]]
Y :  0.5

i :  [2, 3, 4, 5] 6
X :  [[0.2], [0.3], [0.4], [0.5]]
Y :  0.6

i :  [3, 4, 5, 6] 7
X :  [[0.3], [0.4], [0.5], [0.6]]
Y :  0.7

i :  [4, 5, 6, 7] 8
X :  [[0.4], [0.5], [0.6], [0.7]]
Y :  0.8

i :  [5, 6, 7, 8] 9
X :  [[0.5], [0.6], [0.7], [0.8]]
Y :  0.9



In [2]:
import numpy as np

X = np.array(X); Y = np.array(Y)
for i in range(len(X)):
    print(X[i], Y[i])

print(X[i].shape)

[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9
(4, 1)


In [3]:
# 7.2.1 SimpleRNN Layer

import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[4,1]),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 10)                120       
_________________________________________________________________
dense (Dense)                (None, 1)                 11        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.fit(X, Y, epochs=100, verbose=0)
print(model.predict(X))

[[0.4412729 ]
 [0.5478577 ]
 [0.63467485]
 [0.70487523]
 [0.7622538 ]
 [0.80991054]]


In [5]:
print(model.predict(np.array([[[-0.1], [0], [0.1], [0.2]]])))

[[0.31488687]]


In [6]:
# 7.2.2 LSTM Layer

X = list(); Y = list();

for i in range(3000):
    lst = np.random.rand(100) #100 numbers of btwn 0 and 1
    idx = np.random.choice(100, 2, replace=False)
    zeros = np.zeros(100)
    zeros[idx] = 1 #only two numbers are 1 in 100 float numbers

    



[0.64775436 0.12633617 0.03373626 0.36035064 0.86457799 0.36290215
 0.93158461 0.82503338 0.91548992 0.05627579 0.06458251 0.46695309
 0.3772576  0.91658411 0.54333136 0.49193121 0.18569076 0.95516053
 0.37851425 0.72593297 0.34118923 0.60287529 0.06159347 0.02527697
 0.79078128 0.49654243 0.13205301 0.95146505 0.88931511 0.54650202
 0.83617402 0.97206984 0.99932361 0.10206785 0.76778645 0.02164414
 0.57543934 0.88459276 0.00275271 0.2657383  0.63968401 0.40234862
 0.15166527 0.10284473 0.97278335 0.21182836 0.62550116 0.87708114
 0.49405055 0.65369833 0.7848172  0.85660946 0.57957127 0.67481669
 0.15979076 0.44471049 0.46231711 0.94591747 0.91809995 0.87207827
 0.53288336 0.19517114 0.55462359 0.78707027 0.23554282 0.50635338
 0.69053318 0.19148405 0.05220713 0.0620753  0.77561157 0.18881699
 0.04058098 0.14099139 0.64672351 0.43883124 0.58991002 0.42590306
 0.7354072  0.20658852 0.13109335 0.40271048 0.54764861 0.11357018
 0.46175259 0.50997568 0.00816367 0.69049934 0.6415994  0.5844

In [0]:
# 7.2.3 GRU Layer