<a href="https://colab.research.google.com/github/chloepark627/tensorflow_ex/blob/master/ch07_RNN(7_2_layers).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
X = list(); Y = list();
for i in range(6):
    lst = list(range(i, i+4)) 
    #0 / 0,1,2,3
    print('i : ', lst, i+4)

    x = list(map(lambda c:[c/10], lst))
    y = (i+4)/10
    X.append(x)
    Y.append(y)

    print('X : ', x)
    print('Y : ', y)
    print()

i :  [0, 1, 2, 3] 4
X :  [[0.0], [0.1], [0.2], [0.3]]
Y :  0.4

i :  [1, 2, 3, 4] 5
X :  [[0.1], [0.2], [0.3], [0.4]]
Y :  0.5

i :  [2, 3, 4, 5] 6
X :  [[0.2], [0.3], [0.4], [0.5]]
Y :  0.6

i :  [3, 4, 5, 6] 7
X :  [[0.3], [0.4], [0.5], [0.6]]
Y :  0.7

i :  [4, 5, 6, 7] 8
X :  [[0.4], [0.5], [0.6], [0.7]]
Y :  0.8

i :  [5, 6, 7, 8] 9
X :  [[0.5], [0.6], [0.7], [0.8]]
Y :  0.9



In [8]:
import numpy as np

X = np.array(X); Y = np.array(Y)
for i in range(len(X)):
    print(X[i], Y[i])

print(X[i].shape)

[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9
(4, 1)


In [10]:
# 7.2.1 SimpleRNN Layer

import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[4,1]),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 10)                120       
_________________________________________________________________
dense (Dense)                (None, 1)                 11        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.fit(X, Y, epochs=100, verbose=0)
print(model.predict(X))

[[0.48879665]
 [0.5766012 ]
 [0.6501211 ]
 [0.70944744]
 [0.75606865]
 [0.7920678 ]]


In [12]:
print(model.predict(np.array([[[-0.1], [0], [0.1], [0.2]]])))

[[0.3887363]]


In [0]:
# 7.2.2 LSTM Layer

